#!/usr/bin/ruby

require 'find'

@haml_cmd = 'haml'
@compass_cmd = 'compass compile'
@coffee_cmd = 'cake build'

files = {}

def compile_file(f, file_out)
  cmd = nil
  
  case f
    when /\.coffee$/ : cmd = @coffee_cmd
    when /\.haml$/
      cmd = @haml_cmd
      file_out["src/haml/"] = "public/"
      file_out[".haml"] = ".html"
      cmd += " " + f + " " + file_out
    when /\.scss$/, /\.sass$/ : cmd = @compass_cmd
  end
  
  if cmd != nil
    puts "# Run: #{cmd} (adjusted)"
    output = `#{cmd}`
    print output
  end
  
end

# Go through all files in src
Find.find('src/') do |f|
  ctime = File.ctime(f).to_i
  
  case f
  when /\.svn/ # skip all .svn files
  else
    if ctime != files[f]
      files[f] = ctime
      f_out = f.clone
      puts "# recompiling: #{f}" 
      compile_file f, f_out
    end
  end
end


